apiVersion: v1
kind: ConfigMap
metadata:
  name: homework-config
  labels:
    {{- include "homework.labels" . | nindent 4 }}
data:
  #db_name: "test"
  #MYSQL_SERVICE_HOST: "localhost"
  MYSQL_SERVICE_PORT: "3603"